### ISSUE TITLE
Feature: Support for Scikit-Learn v1.7+ Compatibility

### ISSUE THREAD

**Issue by RHammond2** [dswah/pyGAM#422]
It seems that for `scikit-learn>=1.7` there is a new requirement to implement `__sklearn_tags__`. I came across [this version pinning workaround](https://stackoverflow.com/questions/79290968/super-object-has-no-attribute-sklearn-tags) from an XGBoost issue for continuing to use scikit-learn and PyGAM together in the meantime. The change to scikit-learn means that any model training functionality cannot be run with PyGAM models for the latest releases of scikit-learn. I don't believe this is an immediate need, but it would be great if it could be addressed at some point.

### Failing Environment settings
 
* Python 3.14
* scikit-learn>1.6.1
* pygam>=0.11

### Successful workaround environment settings

* Python 3.14
* scikit-learn<1.7
* pygam>=0.11 

### In-code call

The failing setup can boiled down to the following, but comes from [OpenOA](https://github.com/NREL/OpenOA/blob/main/openoa/utils/machine_learning_setup.py#L194).

```python
import numpy as np
from pygam import GAM
from sklearn.metrics import r2_score, make_scorer
from sklearn.model_selection import KFold, RandomizedSearchCV

scorer = make_scorer(r2_score, greater_is_better=True)
random_search = RandomizedSearchCV(
    GAM,
    cv=KFold,
    param_distributions={"n_splines": np.arange(5, 40)},
    n_iter=20,
    scoring=scorer,
    verbose=0,
    return_train_score=True,
)
random_search.fit(X, y)  # X and y 
```

### Relevant traceback

```python
estimator = GAM(callbacks=['deviance', 'diffs'], distribution='normal', 
   fit_intercept=True, link='identity', max_iter=100, terms='auto', 
   tol=0.0001, verbose=False)

    def get_tags(estimator) -> Tags:
        """Get estimator tags.
    
        :class:`~sklearn.BaseEstimator` provides the estimator tags machinery.
    
        For scikit-learn built-in estimators, we should still rely on
        `self.__sklearn_tags__()`. `get_tags(est)` should be used when we
        are not sure where `est` comes from: typically
        `get_tags(self.estimator)` where `self` is a meta-estimator, or in
        the common checks.
    
        .. versionadded:: 1.6
    
        Parameters
        ----------
        estimator : estimator object
            The estimator from which to get the tag.
    
        Returns
        -------
        tags : :class:`~.sklearn.utils.Tags`
            The estimator tags.
        """
    
        try:
            tags = estimator.__sklearn_tags__()
        except AttributeError as exc:
            if "object has no attribute '__sklearn_tags__'" in str(exc):
                # Happens when `__sklearn_tags__` is implemented by calling
                # `super().__sklearn_tags__()` but there is no `__sklearn_tags__`
                # method in the base class. Typically happens when only inheriting
                # from Mixins.
    
>               raise AttributeError(
                    f"The following error was raised: {exc}. It seems that "
                    "there are no classes that implement `__sklearn_tags__` "
                    "in the MRO and/or all classes in the MRO call "
                    "`super().__sklearn_tags__()`. Make sure to inherit from "
                    "`BaseEstimator` which implements `__sklearn_tags__` (or "
                    "alternatively define `__sklearn_tags__` but we don't recommend "
                    "this approach). Note that `BaseEstimator` needs to be on the "
                    "right side of other Mixins in the inheritance order."
                )
E               AttributeError: The following error was raised: 'GAM' object has no attribute '__sklearn_tags__'. It seems that there are no classes that implement `__sklearn_tags__` in the MRO and/or all classes in the MRO call `super().__sklearn_tags__()`. Make sure to inherit from `BaseEstimator` which implements `__sklearn_tags__` (or alternatively define `__sklearn_tags__` but we don't recommend this approach). Note that `BaseEstimator` needs to be on the right side of other Mixins in the inheritance order.

../../../miniconda3/envs/openoa-nrel/lib/python3.14/site-packages/sklearn/utils/_tags.py:283: AttributeError
```

**Comment by fkiraly** [comment]
Yes, compatibility needs to be upgraded and tests should be added.

FYI, you may like to consider using the `skpro` interface of `pygam` instead - it is very similar to `scikit-learn` but also provides the full probabilistic output type:
https://skpro.readthedocs.io/en/latest/api_reference/auto_generated/skpro.regression.gam.GAMRegressor.html#skpro.regression.gam.GAMRegressor

You can combine it out-of-the-box with pipelines, grid search, optimization (e.g., using `optuna`) using the estimators in `skpro`.

**Comment by RHammond2** [comment]
Thanks for the tip! It looks promising, so I'll have to dig a bit deeper and test it out.

**Comment by KrishanYadav333** [comment]
Hi, I’m planning to work on improving scikit-learn >=1.7 compatibility, starting with the __sklearn_tags__ requirement and running estimator compliance checks to identify additional API gaps. I’ll start by investigating inheritance structure and estimator checks, and will propose incremental fixes with tests. Please let me know if there are design preferences I should follow.

**Comment by PrajwalaY26** [comment]
Hi,

I noticed that the immediate __sklearn_tags__ compatibility issue for sklearn>=1.7 is being addressed in recent PRs. I would like to contribute by running full check_estimator compliance tests across GAM variants and identifying remaining API inconsistencies (fit/predict signatures, get_params/set_params, clone compatibility, pipeline behavior).

My goal would be to propose incremental fixes with proper unit tests to ensure robust long-term sklearn compatibility beyond the minimal tag requirement.

Please let me know if this aligns with the intended scope for this effort.

**Comment by selcuksntrk** [comment]
Hi @dswah ,

I'm Selcuk Senturk, an AI/ML Engineer at IBM Expert Labs and MSc Computer Science student at Ege University. I'm interested in contributing to this project as part of GSoC 2026.

For GSoC scope I'd like to go deeper than the current PR, a systematic audit and implementation of pyGAM's full sklearn API compliance.

**Some relevant background:** 
During my BSc research at Izmir Institute of Technology I worked on classifying protein families from atomic/molecular structure using tensorflow and at Istanbul Technical University I implemented PCA from scratch in NumPy and validated it against sklearn's PCA, which gave me a solid understanding of how sklearn expects estimators to behave internally in terms of parameter handling, fit state, and output contracts. In production I've used sklearn pipelines at Siskon Software alongside PyTorch, and at KPMG building evaluation tooling for LLM systems, so I've hit the API edge cases this issue is pointing at in real contexts.

So, I think I can contribute to this issue. I would like to discuss further. Also I want to share my LinkledIn profile and resume to introduce myself in detail.

Resume: [Drive](https://drive.google.com/file/d/12NCptLXY1FZIreGX6pGKuQFi17XRQjTQ/view?usp=sharing)
LinkedIn: [Selcuk Senturk](https://www.linkedin.com/in/selcuksntrk/)

**Comment by RHammond2** [comment]
Great to hear, @KrishanYadav333, I don't have any design preferences for the implementation.

**Comment by Mudassiruddin7** [comment]
sklearn 1.7 replaced _more_tags() with sklearn_tags() returning a Tags dataclass. Without it, any sklearn introspection raises AttributeError. Added sklearn_tags() on GAM (regressor tags) and an override on LogisticGAM (classifier tags with ClassifierTags). Fix is in PR, tested against sklearn 1.8.0.

**Comment by varma1221** [comment]
Hi,

I've been exploring this issue as part of my GSoC 2026 preparation, and I wanted to share some observations from going through the codebase and the existing PRs (#427, #431).

PR #427's approach of inheriting from `BaseEstimator` fixes the immediate `__sklearn_tags__` crash, which is great. But while tracing through the code, I noticed there might be a few deeper compatibility gaps that could still cause issues with sklearn workflows. I wanted to check whether these are already known or if I'm missing something:

### a) `get_params()` behavior

The current `Core.get_params()` filters instance attributes by excluding `_`-prefixed ones. But sklearn's contract expects `get_params()` to return exactly the constructor parameters. This mismatch might break `clone()`, `Pipeline`, and `GridSearchCV` in subtle ways.

### b) `set_params()` differences

sklearn's `set_params` supports nested parameter routing (like `estimator__param`). The current implementation uses a `force` flag instead, which could cause issues in meta-estimators.

### c) Mutable defaults in `__init__`

For example, `callbacks=["deviance", "diffs"]` — sklearn expects `__init__` parameters to be reproducible via `clone()`, and mutable defaults can interfere with that.

### d) Estimator type tagging per subclass

`LogisticGAM` is a classifier (it even has `predict_proba`), but right now all subclasses would get tagged the same way. sklearn expects classifiers and regressors to report different tags.

### e) `score()` semantics

sklearn expects `score()` to return accuracy for classifiers and R² for regressors. pyGAM returns explained deviance for all subclasses, which might confuse `cross_val_score`.

I haven't run `sklearn.utils.estimator_checks.check_estimator()` yet, but I think doing that on each GAM subclass would surface exactly which checks pass and which don't. That could help prioritize what to fix first.

I'm sharing this mainly to understand if these points are already being tracked or if I might be overlooking something. Happy to help with any of this.

Thanks for your work on the project.

**Comment by trongjhuongwr** [comment]
Hi @dswah,

I'm Arthur. I'm highly interested in the **Scikit-Learn Interface** project for GSoC 2026.

I’ve been closely following this thread. It's great to see the community momentum! I noticed @Mudassiruddin7's recent PR #475 tackling the `get_params` contract and `score` semantics, and I completely agree with @varma1221's deep-dive observations regarding the remaining API gaps.

Rather than duplicating efforts on the immediate fixes, my GSoC proposal focuses on achieving rigorous compliance with `sklearn.utils.estimator_checks.check_estimator()` across all GAM variants while maintaining library flexibility. My key focus areas for the 175-hour project include:

**1. Testing & Extending Recent Fixes:** Auditing PR #475 and related changes to ensure complete compatibility with `GridSearchCV` and `clone()` across all subclasses (not just `LinearGAM` and `LogisticGAM`).

**2. Resolving Mutable Defaults in `__init__`:** Refactoring attributes like `callbacks=["deviance", "diffs"]` (which currently leak state across cross-validation folds) to comply strictly with scikit-learn's instantiation rules.

**3. Nested Parameter Routing:** Updating the custom `set_params` to fully support scikit-learn's double-underscore syntax (e.g., `estimator__param`), ensuring meta-estimators function perfectly.

**4. Data Validation & Duck Typing Flexibility:** When overhauling the input validation flows (`check_X`, `check_y`) in `fit` and `predict`, I plan to turn off check object classes where appropriate. This preserves Python's duck typing nature, ensuring the models remain highly flexible and seamlessly accept various custom data formats from users within an `sklearn.pipeline.Pipeline`.

Could you let me know if auditing and resolving these deeper, remaining `check_estimator` failures aligns with your vision for the GSoC scope?

Thanks!

**Comment by vkverma9534** [comment]
@_all I’m curious about the long-term direction for sklearn compatibility here. Beyond adding `__sklearn_tags__`, is the goal for pyGAM estimators to eventually pass `sklearn.utils.estimator_checks.check_estimator()` across the main subclasses (e.g., `LinearGAM`, `LogisticGAM`, etc.)?

While looking through the recent discussions and PRs, I noticed a few areas that might affect deeper integration with tools like `Pipeline`, `clone()`, and `GridSearchCV`—for example the current `get_params()` filtering logic vs sklearn’s expectation that it mirrors the `__init__` signature, mutable defaults such as `callbacks=["deviance", "diffs"]`, and estimator-type tagging differences between regression and classification variants.

Would it be preferable to aim for strict sklearn estimator compliance (including parameter routing with `set_params` and correct scoring semantics per estimator type), or is partial compatibility with the main meta-estimators considered sufficient for the library?

**Comment by Karman580** [comment]
Hi all, appreciate the ongoing discussion around scikit-learn ≥1.7 compatibility.While reviewing the repository as part of my preparation for ESoC and GSoC 2026, I worked on a couple of smaller fixes related to sklearn integration.
I’ve opened two PRs addressing related issues:
PR #494 :-Correct LogisticGAM.predict_proba output shape for sklearn compatibility
PR #498 :-Fix sklearn.clone() dropping explicit GAM terms
Both PRs include regression tests and pass the full CI matrix. While these changes don’t address the broader compatibility effort discussed here, they help restore expected behavior for common sklearn workflows.
Happy to review or assist with further improvements related to sklearn compatibility.

**Comment by dkstlzk** [comment]
Hi! I'm planning to apply for ESoC with pyGAM and have recently started contributing with a few bug fixes and compatibility improvements (#527, #516, #515, #510).

I'm particularly interested in helping improve pyGAM's compatibility with the scikit-learn estimator API and ecosystem tools.

Looking forward to contributing further!

**Comment by hharshhsaini** [comment]
Hi @dswah 

I'm **Harsh Saini** (sainiharsh3311@gmail.com) and I've applied for **ESoC 2026** with pyGAM as my project.

This PR (#539) is a demonstration of my contribution and understanding of the codebase. Here's a summary of my approach:

---

**Problem:** scikit-learn >= 1.7 requires all estimators to implement [__sklearn_tags__()](cci:1://file:///Users/harshsaini/Desktop/pyGAM/pygam/pygam.py:205:4-220:41) or inherit from `BaseEstimator`. pyGAM was missing this, causing `AttributeError` when used with `GridSearchCV`, `RandomizedSearchCV`, and other sklearn meta-estimators.

**My Approach:**

1. **Inherited `BaseEstimator`** - Made [GAM](cci:2://file:///Users/harshsaini/Desktop/pyGAM/pygam/pygam.py:99:0-2477:25) inherit from `sklearn.base.BaseEstimator` (placed first in MRO) so [__sklearn_tags__()](cci:1://file:///Users/harshsaini/Desktop/pyGAM/pygam/pygam.py:205:4-220:41) is available automatically. Added graceful fallback (`BaseEstimator = object`) when sklearn is not installed.

2. **Fixed [get_params()](cci:1://file:///Users/harshsaini/Desktop/pyGAM/pygam/pygam.py:222:4-259:21)** - Used `BaseEstimator.get_params()` for the `deep=False` path (sklearn's clone path) and `Core.get_params()` for the `deep=True` path (pyGAM's internal gridsearch path). This avoids breaking internal machinery while being sklearn-compatible.

3. **Fixed [set_params()](cci:1://file:///Users/harshsaini/Desktop/pyGAM/pygam/core.py:166:4-191:19)** - Replaced delegation to `BaseEstimator.set_params()` (which raised [ValueError](cci:1://file:///Users/harshsaini/Desktop/pyGAM/pygam/tests/test_GAM_methods.py:469:0-495:68) for private/fitted attrs like `_constraint_lam`, [coef_](cci:1://file:///Users/harshsaini/Desktop/pyGAM/pygam/terms.py:1873:4-1898:39)) with direct [setattr()](cci:1://file:///Users/harshsaini/Desktop/pyGAM/pygam/terms.py:448:4-479:59) logic mirroring `Core.set_params`, extended to also handle plural params (`n_splines`, `lam`, etc.).

4. **Added `RegressorMixin` / `ClassifierMixin`** to the appropriate GAM subclasses for proper sklearn type tagging.

5. **Full backward compatibility** - All 170+ existing tests continue to pass. Works with or without sklearn installed.

I would love to contribute more to pyGAM as part of ESoC 2026 - areas I'm interested in include improving sklearn pipeline compatibility, expanding test coverage, and improving documentation.

Looking forward to your feedback

— **Harsh Saini** | sainiharsh3311@gmail.com

**Comment by CRAFTYPROGRAMMER826** [comment]
Hi Daniel,

I'm Om Manuwal, a final-year CS (AI-ML) student interested in the Scikit-Learn Interface project (Issue #422) for GSoC 2026.

**My Background:**
- Worked as a Data Science Intern: Built sklearn pipelines, XGBoost models integrated Mistral Murf and FMP API's
- Strong Python, OOP, pytest
- Experience with sklearn's Pipeline and GridSearchCV

**I've reviewed:**
- Issue #422 (sklearn v1.7+ compatibility)
- sklearn's estimator API requirements
- pyGAM's current implementation

**To scope the proposal correctly, I'd like to understand:**

1. **Compatibility scope:** Should pyGAM classes work with sklearn's Pipeline and GridSearchCV? (These are the main sklearn workflows that require specific API methods like `get_params`, `set_params`)

2. **Testing approach:** Should passing sklearn's `check_estimator()` test be the success criterion? (This is sklearn's standard compatibility test)

3. **Current gaps:** Which sklearn API methods are currently missing or broken in pyGAM? (e.g., `get_params`, `set_params`, `score`)

4. **Backward compatibility:** Should the existing pyGAM API remain unchanged while adding sklearn compatibility?

I'm diving into the codebase to understand issues as good as possible and excited to contribute! for GSoC'26

GitHub:  https://github.com/CRAFTYPROGRAMMER826
linkedin:  https://www.linkedin.com/in/om-manuwal
Email- ommanuwalextra@gmail.com

**Comment by sghosh-04** [comment]
Hi! I'm Sayuri Ghosh, a GSoC 2026 applicant interested in working on the Scikit-Learn Interface project under the GC.OS umbrella.
I've gone through the pyGAM codebase and understand the current gaps missing BaseEstimator inheritance, non-conforming fit or predict signatures, and lack of check_estimator validation. I've drafted a proposal covering these systematically with a 12-week timeline.
Would love any feedback from the mentor @dswah on priorities or anything I may have missed before the March 31 deadline. Happy to share the draft
